### ISSUE TITLE
Nix builds using AppVeyor

### ISSUE THREAD

**Issue by nonperforming** [nonperforming/openspadesplus#50]
For reference, here's yvt's implementation in GitHub Actions

```yml
  build-nix:
    name: Build (Linux + Nix)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build Nix flake
        run: nix build
```

This should be easy to do.
